### ISSUE TITLE
Voeg een forEach toe

### ISSUE THREAD

**Issue by sannevanseeventer** [Daniquedejong/server-side-rendering#4]
https://github.com/Daniquedejong/server-side-rendering/blob/685a1a25fa4ea60aecdb4d0d3f06b6a8b198f883/views/index.ejs#L29

 Voeg een forEach toe om meerdere producten aan te spreken, zo hoef je maar 1 article te maken ipv meerdere.

**Comment by Daniquedejong** [comment]
Afgerond
