### ISSUE TITLE
Geen goed gebruik van Partials (server-side-rendering/views/index.ejs)

### ISSUE THREAD

**Issue by D-spacezero** [Daniquedejong/server-side-rendering#5]
Header partial word wel opgeladen alleen niet op de juiste manier gebruikt. In de die Header partial word enkel de meta data opgehaald. De header content staat nogsteeds in de Index.ejs

**Comment by Daniquedejong** [comment]
In de volgende repo heb ik dit aangepast! Nu staat de header in de head.ejs file.
