### ISSUE TITLE
Embedden van html blokken in ejs-bestanden

### ISSUE THREAD

**Issue by Stefan-Espant** [Daniquedejong/server-side-rendering#6]
Probeer bij grote stukken html deze in aparte ejs bestanden te plaatsen.

https://github.com/Daniquedejong/server-side-rendering/blob/685a1a25fa4ea60aecdb4d0d3f06b6a8b198f883/views/index.ejs#L11-L23

**Comment by Daniquedejong** [comment]
Afgerond!
