### ISSUE TITLE
Wiki iets uitgebreider

### ISSUE THREAD

**Issue by sannevanseeventer** [Daniquedejong/server-side-rendering#7]
In de wiki staat niet genoeg informatie om de definitions of done of de gedragscriteria te behalen. Voeg meer methoden toe bij de Analyse, Ontwerp en Bouwfase.

**Comment by Daniquedejong** [comment]
Ik heb mijn wiki hier aangepast en verder maak ik bij de huidige opdrachten wel veel grotere wiki's!
